### ISSUE TITLE
Libraries do not compile under Linux with the latest ARM compiler

### ISSUE THREAD

**Issue by michaelgregorius** [electro-smith/DaisyWiki#33] opened 2022-06-17 15:05 UTC
The [installation instructions for the Linux toolchain](https://github.com/electro-smith/DaisyWiki/wiki/1d.-Installing-the-Toolchain-on-Linux) point to [this page](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads) to download the toolchain.

I have downloaded [gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz](https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz) but it gives an internal compiler error when trying to build the libraries. You can find the error messages attached: [ErrorMessages.txt](https://github.com/electro-smith/DaisyWiki/files/8928571/ErrorMessages.txt). It mainly consists of the following error:
```
building libDaisy . . .
In file included from src/daisy.h:5,
                 from src/daisy_seed.h:5,
                 from src/daisy_field.h:4,
                 from src/daisy_field.cpp:1:
src/daisy_core.h:81:5: internal compiler error: Illegal instruction
   81 |     return ((float)x - 127.f) * U82F_SCALE;
      |     ^~~~~~
```

### Steps to reproduce
1. Download [gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz](https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz).
2. Decompress the archive.
3. Make sure that the bin folder of the archive is in your path.
4. Go to your working directory of the [DaisyExamples](https://github.com/electro-smith/DaisyExamples) repository.
5. Execute: `./ci/build_libs.sh`

### Workaround
The workaround is to go to the page with the [older releases](https://developer.arm.com/downloads/-/gnu-rm) and to download [gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2](https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2) from there and to use that release.

### Proposed solution
Please consider to update the Wiki page so that it also points to the [older releases](https://developer.arm.com/downloads/-/gnu-rm) of the compilers: https://developer.arm.com/downloads/-/gnu-rm. A pointer to the last known good release would also be helpful.

Please also consider to give more specific information about what is the correct download for the most frequent case of an x86_64 Linux machine. For me it was quite confusing to make sense of all the options on the [ARM page](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads).

**Comment by mfc** [comment] 2022-08-01 17:55
i ran into this exact same issue, and i just updated the wiki to reflect it. i think anyone can update the wiki, which is probably not the best idea :thinking: but at least others won't need to spend time troubleshooting like we did!

**Comment by znmeb** [comment] 2022-08-01 20:29
There's probably also an issue with the source code if a newer compiler throws an error. You should probably open an issue on the library itself.

**Comment by mfc** [comment] 2022-08-02 09:02
oh most certainly, good idea i will open issue and point to here since i'm not interested in troubleshooting further at the moment.

**Comment by as-def** [comment] 2023-01-29 16:01
I compiled using 10.3.1, it worked for me. I will try adjusting the Wiki, I assume if it is still possible, then it is welcome, too?

**Comment by michaelgregorius** [comment] 2023-02-01 16:23
> I compiled using 10.3.1, it worked for me. I tried edting the Wiki page, but I thing this is not possible anymore?

Yes, I am also still using `10.3.1 20210824 (release)`. Fortunately, it's still available [here](https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2).

**Comment by michaelgregorius** [comment] 2023-02-01 16:33
## Update for version 12.2.Rel1
Here's an update for version 12.2.Rel1 of the toolchain. The binaries have been downloaded [here](https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz?rev=7bd049b7a3034e64885fa1a71c12f91d&hash=732D909FA8F68C0E1D0D17D08E057619) and print the following version info:
```
$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## Building the libraries

Building the libraries using `./ci/build_libs.sh` yields a warning in `src/per/sai.cpp` when "libDaisy" is built. However, both libraries are built:
```
building libDaisy . . .
src/per/sai.cpp: In member function 'daisy::SaiHandle::Result daisy::SaiHandle::Impl::DeInit()':
src/per/sai.cpp:210:17: warning: the address of 'daisy::SaiHandle::Impl::config_' will never be NULL [-Waddress]
  210 |     if(&config_ == nullptr)
      |        ~~~~~~~~~^~~~~~~~~~
src/per/sai.cpp:34:23: note: 'daisy::SaiHandle::Impl::config_' declared here
   34 |     SaiHandle::Config config_;
      |                       ^~~~~~~
arm-none-eabi-ar: creating build/libdaisy.a
done.
building DaisySP . . .
done.
```
## Building the examples
Building the examples with `./ci/build_examples.py` yields lots of warnings about functions that are not implemented. Examples:
```
closer.c:(.text._close_r+0xc): warning: _close is not implemented and will always fail
fstatr.c:(.text._fstat_r+0xe): warning: _fstat is not implemented and will always fail
isattyr.c:(.text._isatty_r+0xc): warning: _isatty is not implemented and will always fail
lseekr.c:(.text._lseek_r+0x10): warning: _lseek is not implemented and will always fail
readr.c:(.text._read_r+0x10): warning: _read is not implemented and will always fail
writer.c:(.text._write_r+0x10): warning: _write is not implemented and will always fail
[...]/arm-none-eabi/bin/ld: warning: build/Midi.elf has a LOAD segment with RWX permissions
[...]
```

## Comparison to 10.3.1
None of the warnings above are present when building with 10.3.1.

**Comment by stephenhensley** [comment] 2023-02-13 17:20
Just wanted to chime in here:

We currently do not support arm-toolchain at versions >= 11.
This is a known issue, and all pre-bundled toolchains have a compatible  version.

The [Installing the Toolchain on Linux](https://github.com/electro-smith/DaisyWiki/wiki/1d.-Installing-the-Toolchain-on-Linux) page has been updated to point at a compatible toolchain.

---

I believe doing an update to the entire HAL and included Middlewares will resolve most issues with using the v11/v12 compiler. However, we have not had time to do this, and it will require some migration of the library codebase to accommodate any changes in the HAL, etc.

**Comment by takumi-ogata** [comment] 2023-08-08 20:25
Since we address in the DaisyWiki itself that versions >= 11 are not supported, we'll close this issue. 

Since we're still working towards it, we wanted to include the following information before closing.
Until the HAL (within libDaisy) gets updated, the latest version of the ARM toolchain is not guaranteed to work. Users are advised to download the last confirmed link pointed to on the Linux page (updated after our previous comment on this thread back in February 2023). 
There is an open PR (libDaisy#582) that updates the HAL if anyone wants to try it prematurely.

**Closed by takumi-ogata** 2023-08-08 20:25 UTC

**Comment by michaelgregorius** [comment] 2024-05-09 18:46
For me it's now also working with "arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi". See #538 for more details.
